export const projectTags = [
  // Casual Project/Event Tags
  "Weekend Project",
  "DIY",
  "Crafting",
  "Home Improvement",
  "Gardening",
  "Cooking",
  "Baking",
  "Recipe Sharing",
  "Hiking Adventures",
  "Photography",
  "Travel Diaries",
  "Fitness Challenge",
  "Pet Projects",
  "Book Club",
  "Movie Night",
  "Game Night",
  "Community Event",
  "Local Meetup",
  "Volunteering",
  "Fundraiser",
  "Charity Event",
  "Creative Writing",
  "Art Exhibition",
  "Music Festival",
  "Concert Review",
  "Family Reunion",
  "Anniversary Celebration",
  "Birthday Party",
  "Theme Party",
  "Camping Trip",
  "Road Trip",
  "Exploring Nature",
  "Cultural Event",
  "Craft Fair",
  "Food Festival",
  "Sports Event",
  "Picnic",
  "Karaoke Night",
  "Quarantine Hobby",
  "Sustainability Challenge",
  "Mindfulness",
  "Wellness Retreat",
  "Skill Share",
  "Photo Walk",
  "Painting",
  "Sketching",
  "Sculpture",
  "Knitting",
  "Sewing",
  "Woodworking",
  "Model Building",
  "Collecting",
  "Writing Challenge",
  "Blogging",
  "Vlogging",
  "Podcasting",
  "Music Production",
  "Film Making",
  "Dance Challenge",
  "Fitness Journey",
  "Home Brew",
  "Cosplay",
  "Gaming",
  "Anime",
  "Comic Books",
  "Seasonal Decor",
  "Holiday Crafts",
  "Gift Giving",
  "Holiday Parties",
  "Neighborhood Cleanup",
  "Art Class",
  "Cooking Class",
  "Film Screening",
  "Pet Adoption Event",
  "Nature Walk",
  "Scavenger Hunt",
  "Trivia Night",
  "Potluck Dinner",
  "Community Gardening",
  "Local Art Show",
  "Open Mic Night",
  "Street Fair",
  "Food Truck Festival",
  "Yoga in the Park",
  "Farmers Market",
  "Sports League",
  "Volunteer Day",
  "Public Speaking",
  "Mentoring Program",
  "Book Fair",
  "Craft Workshop",
  "Music Jam Session",
  "Photography Contest",
  "Digital Nomad Meet-up",
  "Start-up Weekend",
  "Hackathon",
  "Co-working Space",
  "Skill Exchange",
  "Online Workshop",
  "Networking Event",

  // Serious Project Tags
  "Business Strategy",
  "Market Research",
  "Financial Analysis",
  "Project Management",
  "Software Development",
  "Data Analysis",
  "Digital Marketing",
  "Social Media Strategy",
  "Content Marketing",
  "SEO Optimization",
  "Brand Development",
  "Product Launch",
  "Risk Assessment",
  "Change Management",
  "Organizational Development",
  "Supply Chain Management",
  "Quality Assurance",
  "Regulatory Compliance",
  "Environmental Sustainability",
  "Healthcare Initiative",
  "Technology Integration",
  "User Experience Design",
  "Agile Methodology",
  "Lean Startup",
  "Entrepreneurship",
  "Corporate Social Responsibility",
  "Public Relations",
  "Crisis Management",
  "Training and Development",
  "E-commerce Strategy",
  "Customer Relationship Management",
  "Human Resources Development",
  "Performance Improvement",
  "Diversity and Inclusion",
  "Research and Development",
  "Innovative Solutions",
  "Strategic Planning",
  "Community Outreach",
  "Policy Development",
  "Advocacy Campaign",
  "Grant Writing",
  "Volunteer Management",
  "Impact Assessment",
  "Business Development",
  "Technical Writing",
  "Information Technology Management",
  "Cybersecurity Project",
  "Artificial Intelligence Implementation",
  "Machine Learning Project",
  "Blockchain Initiative",
  "Health and Wellness Program",

  // Education Tags
  "Educational Workshop",
  "Online Course",
  "Certification Program",
  "School Project",
  "Research Project",
  "Curriculum Development",
  "Teaching Strategies",
  "Student Engagement",
  "Peer Tutoring",
  "Mentorship Program",
  "Literacy Program",
  "STEM Education",
  "Language Learning",
  "Educational Technology",
  "Classroom Management",
  "Community Education",
  "Adult Education",
  "Early Childhood Education",
  "Special Education",
  "College Preparation",
  "Study Group",
  "Career Development",
  "Scholarship Program",
  "Field Trip",
  "School Fundraiser",

  // Volunteering Tags
  "Community Service",
  "Food Bank Volunteer",
  "Tutoring",
  "Mentorship",
  "Disaster Relief",
  "Animal Shelter Volunteer",
  "Environmental Cleanup",
  "Non-Profit Work",
  "Health Awareness Campaign",
  "Crisis Intervention",
  "Advocacy for the Underprivileged",
  "Senior Care Volunteer",
  "Youth Programs",
  "Literacy Programs",
  "Cultural Exchange",
  "Public Health Initiatives",
  "Disability Services",
  "Civic Engagement",
  "Social Justice Work",
  "Volunteer Recruitment",
  "Charity Fundraiser",

  // Software Industry Tags
  "Web Development",
  "Mobile App Development",
  "Software Testing",
  "DevOps",
  "Cloud Computing",
  "Cybersecurity",
  "Data Science",
  "Machine Learning",
  "Artificial Intelligence",
  "UI/UX Design",
  "API Development",
  "Agile Development",
  "Scrum Methodology",
  "Software Architecture",
  "Version Control",
  "Continuous Integration",
  "Database Management",
  "Front-end Development",
  "Back-end Development",
  "Full-stack Development",
  "Quality Assurance Testing",
  "Technical Support",
  "User Research",
  "System Administration",
  "Networking",
  "Open Source Projects",
  "Blockchain Development",
  "Augmented Reality",
  "Virtual Reality",
  "E-commerce Development",
  "Enterprise Software",
  "Mobile Game Development",
];
